name: CI Pipeline

on:
  push:
    branches:
      - milos-testovi
  pull_request:
    branches:
      - milos-testovi

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run Tests
      working-directory: ./frontend
      run: npm test

    - name: Generate Code Coverage
      working-directory: ./frontend
      run: npm run test:coverage
      env:
        CI: true

    - name: Upload Coverage Report
      working-directory: ./frontend
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage
        path: coverage/
